#pragma once

#define SCANNER_ID "scn_replace_me"

#define FIRMWARE_VERSION "esp32-ble-scanner-1.3.1"
#define HARDWARE_VERSION "esp32"

#define SCAN_DURATION_SECONDS 4
#define SCAN_INTERVAL_MS 5000
#define UPLOAD_INTERVAL_MS 5000
#define HEARTBEAT_INTERVAL_MS 30000
#define CONFIG_REFRESH_INTERVAL_MS 60000
#define OBSERVATION_BUFFER_SIZE 160
#define MAX_UPLOAD_BATCH_SIZE 40
#define MAX_SERIAL_FRAME_OBSERVATIONS 12
#define UPLOAD_JSON_BASE_CAPACITY 2048
#define UPLOAD_JSON_PER_OBSERVATION_CAPACITY 1800
#define DEFAULT_RSSI_MIN_DBM -85
#define SERIAL_CONTROL_MAX_BYTES 2048
#define HTTP_TIMEOUT_MS 10000
#define SERIAL_BRIDGE_RESPONSE_TIMEOUT_MS 60000
#define GATT_ENRICHMENT_QUEUE_SIZE 24
#define GATT_ENRICHMENT_CACHE_SIZE 64
#define GATT_CONNECT_TIMEOUT_SECONDS 3
