#pragma once

#define SCANNER_ID "scn_replace_me"

#define FIRMWARE_VERSION "esp32-ble-scanner-1.6.9"
#define HARDWARE_VERSION "esp32-d0wd-v3"
#define SERIAL_BAUD_RATE 230400

#define SCAN_INTERVAL_MS 5000
#define SCAN_SILENCE_RECOVERY_MS 90000
#define UPLOAD_INTERVAL_MS 5000
#define HEARTBEAT_INTERVAL_MS 30000
#define CONFIG_REFRESH_INTERVAL_MS 5000
#define TRANSPORT_RETRY_BACKOFF_MS 1000
#define OBSERVATION_BUFFER_SIZE 96
#define MAX_UPLOAD_BATCH_SIZE 40
#define MAX_SERIAL_FRAME_OBSERVATIONS 12
#define UPLOAD_JSON_BASE_CAPACITY 2048
#define UPLOAD_JSON_PER_OBSERVATION_CAPACITY 1800
#define DEFAULT_RSSI_MIN_DBM -110
#define SERIAL_RX_BUFFER_SIZE 4096
#define SERIAL_CONTROL_MAX_BYTES 4096
#define HTTP_TIMEOUT_MS 10000
#define SERIAL_BRIDGE_RESPONSE_TIMEOUT_MS 12000
#define TRANSPORT_TASK_STACK_SIZE 32768
#define GATT_ENRICHMENT_QUEUE_SIZE 24
#define GATT_ENRICHMENT_CACHE_SIZE 64
#define GATT_ENRICHMENT_MIN_RSSI_DBM -78
#define GATT_ENRICHMENT_UNNAMED_MIN_RSSI_DBM -65
#define GATT_ENRICHMENT_MIN_INTERVAL_MS 60000
#define GATT_ENRICHMENT_COOLDOWN_MS 21600000
#define GATT_MIN_FREE_HEAP_BYTES 70000
#define GATT_MIN_LARGEST_BLOCK_BYTES 20000
#define GATT_RESULT_MAX_AGE_MS 300000
#define GATT_CONNECT_TIMEOUT_MS 3000
#define GATT_OPERATION_TIMEOUT_MS 6000
#define GATT_WORKER_STACK_SIZE 8192
#define GATT_VALUE_MAX_BYTES 512
#define TRACKING_TARGET_LIMIT 8
#define TRACKING_SAMPLE_BUFFER_SIZE 64
#define TRACKING_NORMAL_DEVICE_SLOTS 96
#define TRACKING_SAMPLE_INTERVAL_MS 200
#define TRACKING_UPLOAD_INTERVAL_MS 500
#define TRACKING_CONFIG_REFRESH_INTERVAL_MS 2000
#define MAX_TRACKING_SERIAL_FRAME_SAMPLES 8
